# Form implementation generated from reading ui file '.\operator_view\operator_view.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(643, 509)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(10, 0, 621, 491))
        self.tabWidget.setObjectName("tabWidget")
        self.parcelMachineTable = QtWidgets.QWidget()
        self.parcelMachineTable.setObjectName("parcelMachineTable")
        self.parcelMachineTable_2 = QtWidgets.QTableWidget(self.parcelMachineTable)
        self.parcelMachineTable_2.setGeometry(QtCore.QRect(0, 0, 601, 371))
        self.parcelMachineTable_2.setObjectName("parcelMachineTable_2")
        self.parcelMachineTable_2.setColumnCount(1)
        self.parcelMachineTable_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.parcelMachineTable_2.setHorizontalHeaderItem(0, item)
        self.orderReviewBtn = QtWidgets.QPushButton(self.parcelMachineTable)
        self.orderReviewBtn.setGeometry(QtCore.QRect(30, 393, 141, 41))
        self.orderReviewBtn.setObjectName("orderReviewBtn")
        self.orderRepairBtn = QtWidgets.QPushButton(self.parcelMachineTable)
        self.orderRepairBtn.setGeometry(QtCore.QRect(230, 390, 131, 41))
        self.orderRepairBtn.setObjectName("orderRepairBtn")
        self.tabWidget.addTab(self.parcelMachineTable, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.logsTable = QtWidgets.QTableWidget(self.tab_2)
        self.logsTable.setGeometry(QtCore.QRect(0, 0, 611, 451))
        self.logsTable.setObjectName("logsTable")
        self.logsTable.setColumnCount(0)
        self.logsTable.setRowCount(0)
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.parcelMachineTable_2.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Numer paczkomatu"))
        self.orderReviewBtn.setText(_translate("Form", "ZLEĆ PRZEGLĄD"))
        self.orderRepairBtn.setText(_translate("Form", "ZLEĆ NAPRAWĘ"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.parcelMachineTable), _translate("Form", "Paczkomaty"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Zdarzenia"))
