# Form implementation generated from reading ui file '.\parcel_machine\parcel_machinev2.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.sendBtn = QtWidgets.QPushButton(Form)
        self.sendBtn.setGeometry(QtCore.QRect(50, 100, 120, 80))
        self.sendBtn.setObjectName("sendBtn")
        self.receiveBtn = QtWidgets.QPushButton(Form)
        self.receiveBtn.setGeometry(QtCore.QRect(240, 100, 120, 80))
        self.receiveBtn.setObjectName("receiveBtn")
        self.phoneNumberEdit = QtWidgets.QLineEdit(Form)
        self.phoneNumberEdit.setGeometry(QtCore.QRect(140, 80, 113, 21))
        self.phoneNumberEdit.setObjectName("phoneNumberEdit")
        self.packageCodeEdit = QtWidgets.QLineEdit(Form)
        self.packageCodeEdit.setGeometry(QtCore.QRect(140, 190, 113, 21))
        self.packageCodeEdit.setObjectName("packageCodeEdit")
        self.smallBtn = QtWidgets.QPushButton(Form)
        self.smallBtn.setGeometry(QtCore.QRect(20, 130, 75, 24))
        self.smallBtn.setObjectName("smallBtn")
        self.mediumBtn = QtWidgets.QPushButton(Form)
        self.mediumBtn.setGeometry(QtCore.QRect(170, 130, 75, 24))
        self.mediumBtn.setObjectName("mediumBtn")
        self.largeBtn = QtWidgets.QPushButton(Form)
        self.largeBtn.setGeometry(QtCore.QRect(280, 130, 75, 24))
        self.largeBtn.setObjectName("largeBtn")
        self.confirmBtn = QtWidgets.QPushButton(Form)
        self.confirmBtn.setGeometry(QtCore.QRect(160, 250, 75, 24))
        self.confirmBtn.setObjectName("confirmBtn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.sendBtn.setText(_translate("Form", "NADAJ"))
        self.receiveBtn.setText(_translate("Form", "ODBIERZ"))
        self.phoneNumberEdit.setPlaceholderText(_translate("Form", "NUMER TELEFONU"))
        self.packageCodeEdit.setPlaceholderText(_translate("Form", "KOD ODBIORU"))
        self.smallBtn.setText(_translate("Form", "MAŁA"))
        self.mediumBtn.setText(_translate("Form", "ŚREDNIA"))
        self.largeBtn.setText(_translate("Form", "DUŻA"))
        self.confirmBtn.setText(_translate("Form", "ZATWIERDŹ"))
